### ISSUE TITLE
Deleted payment methods come back after call to Adyen function

### ISSUE THREAD

**Issue by kyleruscigno** [Adyen/adyen-salesforce-commerce-cloud#667]
**Describe the bug**
After successfully deleting a previously saved payment method (Credit Card) from the user interface in SFCC, Adyen will repopulate the deleted payment methods

**To Reproduce**
1. Delete one or more saved payment methods (Credit Card) from a logged-in user account
2. Click 'Back to My Account' or visit any other route which adyen hooks into with the updateSavedCards() method (PaymentInstruments-SavePayment, Account-Show)
3. Inspecting the customer object at the beginning of the updateSavedCards() method should show the customers wallet reflects the deleted payment instruments. After getOneClickPaymentMethods() is called and new payment instruments are created in updateSavedCards() you should see that any deleted credit cards have returned to the customers wallet

**Expected behavior**
Deleted payment methods should not be recreated after their deletion

**Screenshots**
1. Starting from a state of 3 saved payment methods, delete all payments
<img width="305" alt="Screenshot 2022-06-01 155802" src="https://user-images.githubusercontent.com/22186622/172481182-29483186-ff0b-4510-b4aa-60ebe6327815.png">

2. After Deleting all payments, clicking “Back to My Account” shows no saved payment methods *the issue would also occur at this point if we weren't replacing the “Account-Show” route entirely in our controller, as adyen also updates all saved cards on the account-show route
<img width="269" alt="Screenshot 2022-06-01 155903" src="https://user-images.githubusercontent.com/22186622/172481286-f63d65ca-3ff7-43ae-9b3b-70c657b8ef43.png">

3. Click Add New Payment Method and re-add the card ending in ‘1111’
<img width="281" alt="Screenshot 2022-06-01 155725" src="https://user-images.githubusercontent.com/22186622/172481334-99b6b943-a730-48b7-9561-03ee8099ebac.png">

4. Adyen’s savePayment method will prepend to the PaymentInstruments-SavePayment route and call the “updateSavedCards” function. If you capture the customer object at this moment, you’ll see that their wallet only contains the one pending payment method being added
<img width="738" alt="Screenshot 2022-06-01 161356" src="https://user-images.githubusercontent.com/22186622/172481453-ff4d513e-f3de-4fa5-8f74-7f70c3cec6a5.png">

5. The ‘updateSavedCards’ function deletes all existing saved cards and gets the ones to add via the ‘getOneClickPaymentMethods’ function. When you capture the state of it’s return value, you’ll see it contains all the cards previously removed.
<img width="824" alt="Screenshot 2022-06-01 163138" src="https://user-images.githubusercontent.com/22186622/172481518-2b5db437-1a34-42f4-a50c-c8847104cf57.png">

6. Back in ‘updateSavedCards’ you’ll see the credit cards being added contain the ones that were previously removed in this case the one ending in 0007
<img width="924" alt="Screenshot 2022-06-01 155641" src="https://user-images.githubusercontent.com/22186622/172481652-be82a92f-7d65-46a9-8eb0-660ecdd85dce.png">

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome
 - Version: SFRA 6.0.0, Adyen 21.2.0, SFCC 22.5

**Comment by wboereboom** [comment]
Hi @kyleruscigno,

Thanks for raising this issue and for elaborating on it to this extent.
This behavior should be fixed and we'll be looking into this as soon as possible.

Kind Regards,
Wouter
Adyen

**Comment by codyluth** [comment]
@wboereboom  Any progress on this? We are having this issue as well

**Comment by wboereboom** [comment]
Hi @codyluth,

Unfortunately we have not had the opportunity to start developing a fix. 
I will update this ticket as soon as we get the capacity to start working on this.

Kind Regards,
Wouter
Adyen

**Comment by wboereboom** [comment]
Just an update on this thread:

We have not been able to reproduce this issue on v22.1.0
Please let me know if this issue persists for you on this version so we can continue our investigation.

Kind Regards,
Wouter
Adyen

**Comment by codyluth** [comment]
@wboereboom Thanks for getting back to us.  Our QA team re-tested and it seems we are still having this issue with our saved payment methods.  We are on v22.1.1 of the Adyen cartridge.

**Comment by lemonxtt** [comment]
@codyluth the issue is fixed here: https://github.com/Adyen/adyen-salesforce-commerce-cloud/pull/811

**Comment by codyluth** [comment]
@lemonxtt Thanks Lemonxtt.

I figured out that was the issue last month while working on an unrelated issue we were having. I forgot to update this thread with the info I had found, but it seems I didn't need too.

I am glad it will be fixed for the next cartridge update!
